#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 26 17:09:14 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=AuroraLite_1.0.1.zip
